// Catálogo de Nací Reina Calzados.
// Lo usan la página (para mostrar los productos) y el servidor (para cobrar el precio correcto).
// precio: 0 = "Consultar precio" (no se puede pagar online hasta que tenga precio).
// Un color puede tener su propio precio (precio dentro del color); si no, usa el del modelo.
// foto: archivo dentro de la carpeta fotos/. Un color puede tener su propia foto.
(function (catalogo) {
  if (typeof module !== "undefined" && module.exports) module.exports = catalogo;
  else window.CATALOGO = catalogo;
})({
  // WhatsApp del local: 549 + código de área sin 0 + número sin 15. Ej: 5491123456789
  whatsapp: "",

  local: { direccion: "Av. de Mayo 1614, Ramos Mejía", cp: "1704" },

  envio: {
    // Envío gratis cuando los productos suman este monto o más. 0 = sin envío gratis.
    gratisDesde: 150000,
    // Transportista preferido: si Andreani cotiza, se muestran solo sus opciones.
    transportista: "andreani",
    // Caja de cada par (peso en gramos, medidas en cm). Andreani cobra según peso y tamaño.
    // Un producto puede usar otra caja con  caja: "bota-alta".
    cajas: {
      "botas":      { peso: 1500, alto: 13, ancho: 30, largo: 35 },
      "bota-alta":  { peso: 2000, alto: 14, ancho: 32, largo: 45 },
      "zapatos":    { peso: 1100, alto: 12, ancho: 21, largo: 32 },
      "zapatillas": { peso: 1100, alto: 13, ancho: 22, largo: 33 },
      "sandalias":  { peso: 900,  alto: 12, ancho: 21, largo: 32 },
      "suecos":     { peso: 900,  alto: 12, ancho: 21, largo: 32 }
    },
    // Solo se usa mientras Zipnova no esté configurado: costo fijo por zona.
    zonasDeRespaldo: { "CABA": 5000, "Buenos Aires": 6500, "resto": 9500 }
  },

  productos: [
    {id:1,cat:"botas",caja:"bota-alta",nombre:"Bota texana bordada",desc:"Caña alta, bordado western, taco de madera.",precio:45000,talles:[35,36,37,38,39,40],colores:[{id:"marron",nombre:"Chocolate",hex:"#5A2A1E",precio:48000,foto:"fotos/bota-texana-bordada-marron.jpg"},{id:"blanco",nombre:"Blanco",hex:"#F2EFEA",precio:45000,foto:"fotos/bota-texana-bordada-blanca.webp"}]},
    {id:2,cat:"botas",nombre:"Bota texana corta",desc:"Caña corta, cierre lateral, puntera bordada.",precio:28000,talles:[35,36,37,38,39,40],colores:[{id:"suela",nombre:"Suela",hex:"#7B3F1E",foto:"fotos/bota-texana-corta-marron.webp"}]},
    {id:13,cat:"botas",nombre:"Bota texana punta cuadrada",desc:"Caña media, cierre lateral, taco ancho.",precio:28000,talles:[35,36,37,38,39,40],colores:[{id:"marron",nombre:"Marrón",hex:"#7A4A2A",foto:"fotos/bota-texana-punta-cuadrada-marron.jpg"},{id:"negro",nombre:"Negro",hex:"#1C1C1C"}]},
    {id:14,cat:"botas",nombre:"Bota texana con tachas",desc:"Tachas doradas y plateadas, cierre lateral.",precio:45000,talles:[35,36,37,38,39,40],colores:[{id:"blanco",nombre:"Blanco",hex:"#F2EFEA",foto:"fotos/bota-texana-tachas-blanca.jpg"},{id:"negro",nombre:"Negro",hex:"#1C1C1C"}]},
    {id:9,cat:"botas",nombre:"Bota corta con tachas",desc:"Elásticos laterales, tachas, taco de madera.",precio:30000,talles:[35,36,37,38,39,40],colores:[{id:"marron",nombre:"Marrón",hex:"#4E2E1E",foto:"fotos/bota-corta-tachas-marron.jpg"},{id:"negro",nombre:"Negro",hex:"#1C1C1C"}]},
    {id:3,cat:"botas",caja:"bota-alta",nombre:"Bota texana con flecos",desc:"Gamuza, flecos laterales y tachas.",precio:55000,talles:[35,36,37,38,39,40],colores:[{id:"marron",nombre:"Marrón",hex:"#3E2418",foto:"fotos/bota-flecos-tachas-marron.jpg"},{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/bota-flecos-tachas-negra.jpg"}]},
    {id:12,cat:"botas",caja:"bota-alta",nombre:"Bota caña alta con flecos",desc:"Caña fruncida, tiras con argollas, punta fina.",precio:50000,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/bota-cana-alta-flecos-negra.webp"},{id:"blanco",nombre:"Blanco",hex:"#F2EFEA"}]},
    {id:4,cat:"botas",nombre:"Bota caña fruncida",desc:"Caña ancha fruncida, punta fina, taco bajo.",precio:40000,talles:[35,36,37,38,39,40],colores:[{id:"marron",nombre:"Marrón",hex:"#5C3A26",foto:"fotos/bota-fruncida-marron.webp"},{id:"blanco",nombre:"Blanco",hex:"#F2EFEA",foto:"fotos/bota-fruncida-blanca.jpg"},{id:"negro",nombre:"Negro",hex:"#1C1C1C"},{id:"bordo",nombre:"Bordó",hex:"#5E1A22"}]},
    {id:5,cat:"botas",nombre:"Bota fruncida con hebillas",desc:"Caña fruncida, dos hebillas, taco chino.",precio:40000,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/bota-hebillas-negra.jpg"}]},
    {id:6,cat:"zapatos",nombre:"Zapato acordonado con tachas",desc:"Plataforma dentada, tachas plateadas.",precio:0,talles:[35,36,37,38,39,40],foto:"fotos/zapato-acordonado-bordo.webp",colores:[{id:"bordo",nombre:"Bordó",hex:"#5E1A22"}]},
    {id:7,cat:"zapatillas",nombre:"Zapatillas Campus",desc:"Gamuza, cordones anchos, suela de goma.",precio:30000,talles:[35,36,37,38,39,40,41,42,43,44],colores:[{id:"verde",nombre:"Verde",hex:"#095D13",foto:"fotos/zapatilla-campus-verde.webp"},{id:"negro",nombre:"Negro",hex:"#000000",foto:"fotos/zapatilla-campus-negra.jpg"}]},
    {id:8,cat:"zapatillas",nombre:"Zapatillas Samba",desc:"Tiras laterales, suela caramelo.",precio:30000,talles:[37,38,39,40,41,42,43,44,45],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/zapatilla-samba-negra.jpg"},{id:"marron",nombre:"Marrón",hex:"#9A5A32",foto:"fotos/zapatilla-samba-marron.jpg"}]},
    {id:10,cat:"zapatillas",nombre:"Zapatillas urbanas gamuza",desc:"Gamuza, cordones beige, suela caramelo.",precio:0,talles:[35,36,37,38,39,40],foto:"fotos/zapatilla-gamuza-marron.jpg",colores:[{id:"marron",nombre:"Marrón",hex:"#3F2E22"}]},
    // Catálogo Pontecomoda (sin precio todavía)
    {id:15,cat:"zapatillas",nombre:"Zapatillas Samba sin talón",desc:"Estilo Samba abierta atrás, se calza como un sueco. Suela caramelo.",precio:0,talles:[35,36,37,38,39,40,41],colores:[{id:"blanco",nombre:"Blanco y negro",hex:"#F2EFEA",foto:"fotos/zapatilla-samba-sueco-blanca.jpg"}]},
    {id:16,cat:"sandalias",nombre:"Sandalia plataforma Verona",desc:"Dos tiras anchas lisas, con ojalillos o con tachas, hebilla al tobillo y base alta.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro con ojalillos",hex:"#1C1C1C",foto:"fotos/sandalia-plataforma-ojalillos-negra.jpg"},{id:"tachas",nombre:"Negro con tachas",hex:"#2E2E2E",foto:"fotos/sandalia-plataforma-tachas-negra.jpg"},{id:"liso",nombre:"Negro liso",hex:"#111111",foto:"fotos/sandalia-plataforma-lisa-negra.jpg"}]},
    {id:17,cat:"suecos",nombre:"Sueco con hebilla",desc:"Tira con hebilla plateada, plantilla de corcho y base de goma. Nueva temporada.",precio:0,talles:[35,36,37,38,39,40,41],colores:[{id:"rafia",nombre:"Rafia marrón",hex:"#6B4A34",foto:"fotos/sueco-rafia-hebilla-marron.jpg"},{id:"animal",nombre:"Animal print",hex:"#B07A3C",foto:"fotos/sueco-hebilla-animal-print.jpg"},{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/sueco-hebilla-negro.jpg"},{id:"suela",nombre:"Suela",hex:"#8A5A34",foto:"fotos/sueco-hebilla-suela.jpg"},{id:"vaca",nombre:"Print vaca",hex:"#F2EFEA",foto:"fotos/sueco-hebilla-vaca.jpg"},{id:"rafianatural",nombre:"Rafia natural",hex:"#E8DCC4",foto:"fotos/sueco-hebilla-rafia-natural.jpg"},{id:"gamuzanegra",nombre:"Gamuza negra",hex:"#15161C",foto:"fotos/sueco-hebilla-gamuza-negra.jpg"},{id:"topo",nombre:"Gamuza gris topo",hex:"#5E5652",foto:"fotos/sueco-hebilla-gamuza-topo.jpg"}]},
    {id:18,cat:"sandalias",nombre:"Sandalia de tiras cruzadas",desc:"Chinela de tiras anchas cruzadas, suela liviana.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/sandalia-tiras-cruzadas-negra.jpg"},{id:"vaca",nombre:"Print vaca",hex:"#F2EFEA",foto:"fotos/sandalia-tiras-cruzadas-vaca.jpg"},{id:"leopardo",nombre:"Animal print",hex:"#B07A3C",foto:"fotos/sandalia-tiras-cruzadas-leopardo.jpg"}]},
    {id:19,cat:"sandalias",nombre:"Sandalia con abrojo",desc:"Dos tiras con abrojo y tira al talón. Viene en varias combinaciones.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/sandalia-abrojo-negra.jpg"}]},
    {id:20,cat:"zapatillas",nombre:"Zapatillas sin talón con estrella",desc:"Se calzan como un sueco. Estrella al costado, suela blanca.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/zapatilla-sin-talon-estrella-negra.jpg"}]},
    {id:21,cat:"sandalias",nombre:"Sandalia con dos hebillas",desc:"Dos tiras con hebilla plateada, tira al dedo y base acolchada.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/sandalia-dos-hebillas-negra.jpg"}]},
    {id:22,cat:"sandalias",nombre:"Sandalia con hebillas y tira al tobillo",desc:"Tiras anchas con hebilla, plantilla de gamuza y base de goma. Calza hasta el 41.",precio:0,talles:[35,36,37,38,39,40,41],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/sandalia-hebillas-negra.jpg"},{id:"vison",nombre:"Visón",hex:"#A8927E",foto:"fotos/sandalia-hebillas-vison.jpg"}]},
    {id:23,cat:"sandalias",nombre:"Sandalia de taco con plataforma",desc:"Taco ancho, plataforma y pulsera al tobillo con hebilla.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"ojalillos",nombre:"Negro con ojalillos",hex:"#1C1C1C",foto:"fotos/sandalia-taco-plataforma-ojalillos-negra.jpg"},{id:"liso",nombre:"Negro liso",hex:"#2E2E2E"}]},
    {id:24,cat:"zapatillas",nombre:"Zapatillas urbanas con franja",desc:"Franja en V al costado, detalles de gamuza y suela caramelo.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/zapatilla-franja-negra.jpg"},{id:"bordo",nombre:"Bordó",hex:"#7A1F2B",foto:"fotos/zapatilla-franja-bordo.jpg"}]},
    {id:25,cat:"sandalias",nombre:"Sandalia con tachas y anillo al dedo",desc:"Tiras cruzadas con tachas, anillo al dedo, hebilla al tobillo y base alta.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/sandalia-tachas-dedo-negra.jpg"}]},
    {id:26,cat:"suecos",nombre:"Sueco de gamuza con flecos",desc:"Gamuza, flecos y borlas al frente, plantilla de corcho. Nueva temporada.",precio:0,talles:[35,36,37,38,39,40,41],colores:[{id:"marron",nombre:"Chocolate",hex:"#3E2A20",foto:"fotos/sueco-gamuza-flecos-marron.jpg"}]},
    {id:27,cat:"suecos",nombre:"Sueco de gamuza con borlas",desc:"Gamuza suave, tiras cruzadas con borlas y base de goma. Nueva temporada.",precio:0,talles:[35,36,37,38,39,40,41],colores:[{id:"gris",nombre:"Gris perla",hex:"#C9CFD6",foto:"fotos/sueco-gamuza-borlas-gris.jpg"}]},
    {id:28,cat:"zapatillas",nombre:"Zapatillas clásicas con plataforma",desc:"Lisas, con cordones y base blanca alta. Combinan con todo.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"blanco",nombre:"Blanco",hex:"#F4F1EC",foto:"fotos/zapatilla-clasica-blanca.jpg"},{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/zapatilla-clasica-negra.jpg"},{id:"camel",nombre:"Camel",hex:"#B07A4E",foto:"fotos/zapatilla-clasica-camel.jpg"},{id:"plateado",nombre:"Plateado",hex:"#BFC3C7",foto:"fotos/zapatilla-clasica-plateada.jpg"},{id:"champagne",nombre:"Champagne",hex:"#D4B79A",foto:"fotos/zapatilla-clasica-champagne.jpg"}]},
    {id:29,cat:"borcegos",nombre:"Borcego con pulsera de tachas",desc:"Estilo chelsea con elásticos, pulsera con tachas y suela dentada alta.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/borcego-pulsera-tachas-negro.jpg"}]},
    {id:30,cat:"zapatillas",nombre:"Zapatillas urbanas Vitto",desc:"Plataforma blanca con suela caramelo y detalles cosidos.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"blanco",nombre:"Blanco",hex:"#F4F1EC",foto:"fotos/zapatilla-vitto-blanca.jpg"},{id:"camel",nombre:"Camel",hex:"#B07A4E",foto:"fotos/zapatilla-vitto-camel.jpg"},{id:"pastel",nombre:"Pastel (verde agua y celeste)",hex:"#A8DCC4",foto:"fotos/zapatilla-vitto-pastel.jpg"},{id:"violeta",nombre:"Violeta y negro",hex:"#6B3FC4",foto:"fotos/zapatilla-vitto-violeta.jpg"}]},
    {id:31,cat:"zapatillas",nombre:"Zapatillas estilo Samba",desc:"Tres tiras al costado, puntera de gamuza y suela caramelo. Damas del 35 al 41, hombre del 39 al 44.",precio:0,talles:[35,36,37,38,39,40,41,42,43,44],colores:[{id:"blanconegro",nombre:"Blanco y negro",hex:"#F4F1EC",foto:"fotos/zapatilla-samba-blanca-negra.jpg"},{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/zapatilla-samba-negra-pc.jpg"},{id:"blanco",nombre:"Blanco, celeste y dorado",hex:"#F4F1EC",foto:"fotos/zapatilla-samba-blanca-celeste.jpg"},{id:"celeste",nombre:"Celeste",hex:"#A9C8E8",foto:"fotos/zapatilla-samba-celeste.jpg"},{id:"bordo",nombre:"Bordó",hex:"#7A1F3D",foto:"fotos/zapatilla-samba-bordo.jpg"},{id:"animal",nombre:"Animal print",hex:"#B07A3C",foto:"fotos/zapatilla-samba-animal-print.jpg"},{id:"blancobordo",nombre:"Blanco, bordó y dorado",hex:"#7A1F3D",foto:"fotos/zapatilla-samba-blanca-bordo.jpg"},{id:"beigecafe",nombre:"Beige y café",hex:"#9A5A32",foto:"fotos/zapatilla-samba-beige-cafe.jpg"},{id:"verde",nombre:"Verde",hex:"#1E8A4C",foto:"fotos/zapatilla-samba-verde.jpg"},{id:"rojo",nombre:"Rojo",hex:"#C4161C",foto:"fotos/zapatilla-samba-roja.jpg"},{id:"fucsia",nombre:"Fucsia",hex:"#D6246E",foto:"fotos/zapatilla-samba-fucsia.jpg"},{id:"verdeoscuro",nombre:"Verde inglés",hex:"#1F5E3A",foto:"fotos/zapatilla-samba-verde-oscuro.jpg"},{id:"blancobordogris",nombre:"Blanco, bordó y gris",hex:"#8A8D91",foto:"fotos/zapatilla-samba-blanca-bordo-gris.jpg"},{id:"chocolate",nombre:"Chocolate",hex:"#4E2E1E",foto:"fotos/zapatilla-samba-chocolate.jpg"}]},
    {id:32,cat:"borcegos",nombre:"Borcego con cordones",desc:"Acordonado, con base dentada súper liviana.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/borcego-cordones-negro.jpg"},{id:"marron",nombre:"Marrón",hex:"#4E3428",foto:"fotos/borcego-cordones-marron.jpg"},{id:"blancocadena",nombre:"Blanco con cadena",hex:"#F2EFEA",foto:"fotos/borcego-cordones-blanco-cadena.jpg"}]},
    {id:33,cat:"botas",nombre:"Bota texana corta con rayo",desc:"Detalle de rayo en gamuza con tachas, cierre lateral y taco de madera.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/bota-texana-rayo-negra.jpg"},{id:"suela",nombre:"Suela",hex:"#B8743E",foto:"fotos/bota-texana-rayo-suela.jpg"}]},
    {id:34,cat:"borcegos",nombre:"Borcego con elásticos Keyla",desc:"Estilo chelsea con elásticos a los costados y plataforma dentada.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/borcego-elastico-keyla-negro.jpg"}]},
    {id:35,cat:"sandalias",nombre:"Sandalia con aplique dorado",desc:"Tiras cruzadas, anillo al dedo con aplique dorado y doble pulsera con hebilla.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/sandalia-india-apliques-negra.jpg"}]},
    {id:36,cat:"sandalias",nombre:"Sandalia de tiras metalizadas",desc:"Dos tiras anchas, una metalizada y otra con brillos, hebilla al tobillo y base cómoda.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"plateado",nombre:"Plateado",hex:"#C9CDD2",foto:"fotos/sandalia-roma-plateada.jpg"},{id:"rose",nombre:"Rosé con glitter",hex:"#D9A89A",foto:"fotos/sandalia-roma-rose.jpg"},{id:"dorado",nombre:"Dorado con glitter",hex:"#C9A45C",foto:"fotos/sandalia-roma-dorada.jpg"}]},
    {id:37,cat:"zapatillas",nombre:"Zapatillas botita con estrella",desc:"Caña alta de gamuza, estrella al costado y suela blanca.",precio:0,talles:[35,36,37,38,39,40,41],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/zapatilla-botita-estrella-negra.jpg"},{id:"animal",nombre:"Animal print con estrella dorada",hex:"#B07A3C",foto:"fotos/zapatilla-botita-estrella-animal-print.jpg"}]},
    {id:38,cat:"zapatillas",nombre:"Zapatillas con yute y estrella",desc:"Detalles de yute, estrella al costado y plataforma blanca.",precio:0,talles:[35,36,37,38,39,40,41],colores:[{id:"camel",nombre:"Camel",hex:"#B08A5E",foto:"fotos/zapatilla-yute-camel.jpg"}]},
    {id:39,cat:"zapatillas",nombre:"Zapatillas con brillo Lurex",desc:"Tela con brillo, detalles charolados y plataforma blanca.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"plateado",nombre:"Plateado",hex:"#C9CDD2",foto:"fotos/zapatilla-lurex-plateada.jpg"},{id:"plomo",nombre:"Gris plomo",hex:"#6E7075",foto:"fotos/zapatilla-lurex-plomo.jpg"}]},
    {id:40,cat:"borcegos",nombre:"Borcego base tractor",desc:"Cuero con cordones y base tractor alta en tono arena.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"suela",nombre:"Suela",hex:"#A8683A",foto:"fotos/borcego-tractor-suela.jpg"}]},
    {id:41,cat:"borcegos",nombre:"Borcego Gaby",desc:"Acordonado, caña corta y plataforma dentada.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/borcego-gaby-negro.jpg"}]},
    {id:42,cat:"zapatillas",nombre:"Zapatillas con animal print y tachas",desc:"Negras con detalles animal print, tachas plateadas y plataforma blanca.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro y animal print",hex:"#1C1C1C",foto:"fotos/zapatilla-vicky-animal-print.jpg"}]},
    {id:43,cat:"botas",nombre:"Bota texana baja",desc:"Caña baja con recortes texanos, cierre lateral y taco de madera.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/bota-texana-baja-negra.jpg"},{id:"negroblanco",nombre:"Negro y blanco",hex:"#F4F1EC",foto:"fotos/bota-texana-baja-negra-blanca.jpg"},{id:"vibora",nombre:"Víbora",hex:"#4A4550",foto:"fotos/bota-texana-baja-vibora.jpg"}]},
    {id:44,cat:"borcegos",nombre:"Borcego caña alta",desc:"Caña alta acordonada, cierre lateral y plataforma dentada.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/borcego-cana-alta-negro.jpg"}]},
    {id:45,cat:"botas",caja:"bota-alta",nombre:"Bota caña alta con hebillas",desc:"Caña alta con seis hebillas plateadas, correa al tobillo y suela dentada.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/bota-hebillas-malaga-negra.jpg"}]},
    {id:46,cat:"zapatillas",nombre:"Zapatillas urbanas Renata",desc:"Estilo deportivo con cordones gruesos bicolor y base blanca.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/zapatilla-renata-negra.jpg"}]},
    {id:47,cat:"borcegos",nombre:"Borcego caña alta con plataforma",desc:"Caña alta acordonada y plataforma extra alta.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/borcego-cana-alta-plataforma-negro.jpg"}]},
    {id:48,cat:"borcegos",nombre:"Borcego con cierre",desc:"Caña corta lisa, cierre lateral y plataforma dentada.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/borcego-cierre-negro.jpg"}]},
    {id:49,cat:"zapatillas",nombre:"Zapatillas animal print con puntera",desc:"Animal print con puntera y talón negros, suela caramelo.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"animal",nombre:"Animal print y negro",hex:"#B07A3C",foto:"fotos/zapatilla-print-puntera-negra.jpg"}]},
    {id:50,cat:"borcegos",nombre:"Borcego con corderito",desc:"Cuero graneado, cuello de corderito y plataforma dentada. Ideal para el invierno.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/borcego-corderito-negro.jpg"},{id:"suela",nombre:"Suela",hex:"#B8743E",foto:"fotos/borcego-corderito-suela.jpg"}]},
    {id:51,cat:"sandalias",nombre:"Sandalia India con doble pulsera",desc:"Tiras cruzadas, anillo al dedo y doble pulsera al tobillo con hebillas.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/sandalia-india-negra.jpg"},{id:"dorado",nombre:"Dorado",hex:"#C9B27C",foto:"fotos/sandalia-india-dorada.jpg"}]},
    {id:52,cat:"sandalias",nombre:"Chinela plataforma con ojalillos",desc:"Dos tiras con ojalillos y hebillas plateadas sobre base alta.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/chinela-plataforma-ojalillos-negra.jpg"}]},
    {id:53,cat:"sandalias",nombre:"Chinela con strass y anillo al dedo",desc:"Tiras con strass brillante, anillo al dedo y base con estrella.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/chinela-strass-negra.jpg"}]},
    {id:54,cat:"sandalias",nombre:"Chinela estilo Birk",desc:"Dos tiras anchas con hebillas plateadas y plantilla anatómica.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/chinela-birk-negra.jpg"}]},
    {id:55,cat:"sandalias",nombre:"Chinela plataforma con tachas cruzadas",desc:"Tiras cruzadas con tachas y hebillas grandes, base alta dentada.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/chinela-plataforma-tachas-negra.jpg"}]},
    {id:56,cat:"sandalias",nombre:"Sandalia de taco con tiras cruzadas",desc:"Taco ancho, plataforma, tiras cruzadas y doble pulsera al tobillo.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/sandalia-taco-cruzada-negra.jpg"}]},
    {id:57,cat:"zapatillas",nombre:"Zapatillas metalizadas con estrella",desc:"Cuero blanco y negro con detalles metalizados, estrella al costado y base alta.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"oro",nombre:"Oro",hex:"#C9A45C",foto:"fotos/zapatilla-ricky-oro.jpg"},{id:"plata",nombre:"Plata",hex:"#C9CDD2",foto:"fotos/zapatilla-ricky-plata.jpg"}]},
    {id:58,cat:"zapatillas",nombre:"Zapatillas con glitter",desc:"Paneles con glitter, cordones y plataforma blanca. La negra lleva además tachas doradas y detalles charolados.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"negro",nombre:"Negro con tachas",hex:"#1C1C1C",foto:"fotos/zapatilla-paula-negra.jpg"},{id:"blanco",nombre:"Blanco",hex:"#EEE8DF",foto:"fotos/zapatilla-paula-blanca.jpg"}]},
    {id:59,cat:"zapatillas",nombre:"Zapatillas blancas con estrella",desc:"Blancas con estrella y talón de color, plataforma blanca. Varios colores.",precio:0,talles:[35,36,37,38,39,40],colores:[{id:"dorado",nombre:"Dorado",hex:"#C9A45C",foto:"fotos/zapatilla-paris-dorada.jpg"},{id:"fucsia",nombre:"Fucsia",hex:"#E0157F",foto:"fotos/zapatilla-paris-fucsia.jpg"},{id:"verde",nombre:"Verde",hex:"#1E8A4C",foto:"fotos/zapatilla-paris-verde.jpg"},{id:"negro",nombre:"Negro",hex:"#1C1C1C",foto:"fotos/zapatilla-paris-negra.jpg"}]}
  ]
});
